name: Kinko
inputs:
  secrets:
    secret:
      description: Name of the secret to use
      required: true
    api_url:
      description: URL of the Kinko API [e.g. http(s)://(kinko.example.com|
      required: true
    debug:
      description: Enable debug mode to see plain secret output [true|false]
      required: false
      default: false

runs:
  using: docker
  image: Dockerfile
