name: Kinko
inputs:
  secrets:
    secrets:
      description: Name of the secret to use
      required: true
    api_url:
      description: URL of the Kinko API [e.g. http(s)://(kinko.example.com|192.168.255.254)(:port)@token]
      required: true
    debug:
      description: Enable debug mode to see plain secret output [true|false] (default - false)
      required: false
      default: false

runs:
  using: docker
  image: Dockerfile
